---
- name: Check if iipsrv has been installed already
  stat:
    path: "{{ iipsrv_bin }}"
  register: iipsrv_bin_status

- name: Build iipsrv if not installed
  command: /bin/true
  changed_when: iipsrv_bin_status.stat.isdir is not defined
  notify:
    - install build dependencies
    - checkout iipsrv sources
    - build iipsrv
    - remove build dir
    - remove build dependencies

- name: Ensure iipsrv is installed
  meta: flush_handlers

- name: install runtime dependencies
  apt:
    pkg: "{{ iipsrv_runtime_deps }}"

- name: configure iipsrv
  template:
    src: "iipsrv.env.j2"
    dest: "/etc/default/iipsrv"
    mode: 0644
  notify: restart iipsrv service

- name: configure iipsrv service
  template:
    src: "iipsrv.service.j2"
    dest: "/etc/systemd/system/iipsrv.service"
    mode: 0644
  when: ansible_connection != 'docker'
  notify: restart iipsrv service

- name: enable and start iipsrv service
  systemd:
    name: "iipsrv"
    enabled: true
    state: started
  when: ansible_connection != 'docker'
